#baseurl = "/"
baseurl = "https://csama2023.bioconductor.eu"
title = "CSAMA 2023"
theme = ["hugo-universal-theme"]
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"

# Define the number of posts per page
paginate = 50

[menu]

# Main menu

[[menu.main]]
    identifier="home"
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    identifier="about"
    name = "About"
    url  = "/about/"
    weight = 2

[[menu.main]]
    identifier = "programme"
    name = "Programme"
    url  = "/programme-coming-soon/"
    weight = 3

[[menu.main]]
    identifier="registration"
    name = "Registration"
    url  = "/registration-coming-soon/"
    weight = 3

[[menu.main]]
    identifier="venue"
    name = "Venue"
    url  = "/venue/"
    weight = 4
    
[[menu.main]]
    identifier="travel"
    name = "Travel and Accommodation"
    url  = "/travel-and-accommodation/"
    weight = 5

[[menu.main]]
    identifier = "contactus"
    name = "Contact"
    url  = "/contact/"
    weight = 6


# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/Bioconductor"
    pre = "<i class='fab fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 3
    name = "Twitter"
    url = "https://twitter.com/Bioconductor"
    pre = "<i class='fab fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 4
    name = "Email"
    url = "mailto:workshop@bioconductor.org"
    pre = "<i class='fas fa-2x fa-envelope'></i>"

[[menu.topbar]]
    weight = 5
    name = "Slack"
    url = "https://bioc-community.herokuapp.com/"
    pre = "<i class='fab fa-2x fa-slack'></i>"

[params]
    author = "European Bioconductor Society e.V."
    defaultKeywords = ["Bioconductor", "CSAMA", "Bioinformatics", "Training"]

    # Social media
    defaultDescription = "Biological Data Science, 11-16 June 2023, Brixen / Bressanone, Italy"
    default_sharing_image = "img/social_media_image.png"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    # style = "default"
    style = "green"

    about_us = "The European Bioconductor Society e.V. is a registered association in Germany created to support Bioconductor's mission to promote open source software in the life sciences and statistics."
    copyright = "Copyright (c) 2023, <a href='https://bioconductor.eu/'>European Bioconductor Society e.V.</a>"

    # Format dates with Go's time formatting
    date_format = "2 January 2006"

    logo = "img/EuroBioC-logo.png"
    logo_small = "img/EuroBioC-logo.png"
    address = ""

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = false
    text = """<p class="hidden-sm hidden-xs">Join/follow our community</p>
      <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fas fa-phone"></i></a>
      <a href="#" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = false

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = false
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.



[params.lecturers]
    enable = true
    title = "Lecturers and Faculty"
    
[params.overview]
    enable = true
    title = "Overview"
    content = "The one-week intensive summer school **Biological Data Science** teaches advanced computational analyses of modern molecular data types in biology and biomedicine, including single cell and spatial omics. It comprises lectures covering underlying theory and concepts, practical hands-on exercises, and informal discussion sessions. Lecture topics include modern biotechnologies for quantitative measurements, statistical analysis, visualisation, and computational tools. Hands-on exercises are looking at state-of-the-art datasets, using the R / Bioconductor environment. At the end of the course, you should be better able to design, implement and interpret analyses on your own (multi-)omic, single and/or spatial data, adapt and combine different tools, and make informed and scientifically sound choices about analysis strategies."

[params.see_more]
    enable = false
    icon = "far fa-file-alt"
    title = "Do you want to see more?"
    subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
    link_url = "#"
    link_text = "Check other homepages"

[params.sponsors]
    enable = true
    # Sponsors are found in data/sponsors/*.yml
    title = "Organised in collaboration with"
    subtitle = ""

[markup.goldmark.renderer]
unsafe= true
