[build.environment]
  HUGO_VERSION = "0.101.0"

[[headers]]
  for = "/payment"
  [headers.values]
    X-Robots-Tag = "noindex"

[[headers]]
  for = "/success"
  [headers.values]
    X-Robots-Tag = "noindex"

[[headers]]
  for = "/cancellation"
  [headers.values]
    X-Robots-Tag = "noindex"

[[headers]]
  for = "/registration*"
  [headers.values]
    X-Robots-Tag = "noindex"
    
[[headers]]
  for = "/programme*"
  [headers.values]
    X-Robots-Tag = "noindex"
    
[[headers]]
  for = "/installation"
  [headers.values]
    X-Robots-Tag = "noindex"
